# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightprice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='LastSellPrice',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lastSellPriceU',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='latitudeNum',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='longitudeNum',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=200),
            preserve_default=False,
        ),
    ]
