# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rightprice', '0004_auto_20170919_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='LastSellPrice',
            new_name='SellPriceMax',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lastSellPriceU',
            new_name='SellPriceMin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cnpjNum',
            new_name='addressName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dataLastEmitTxt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lastSellDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='placeNum',
        ),
        migrations.RemoveField(
            model_name='product',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='telephoneNum',
        ),
    ]
