# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightprice', '0005_auto_20170921_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='latitudeNum',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitudeNum',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='razaoSocialName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
