# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightprice', '0007_auto_20170922_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
