# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightprice', '0009_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasiaName', models.CharField(max_length=200)),
                ('addressName', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
                ('cepNum', models.CharField(max_length=200)),
                ('cityName', models.CharField(max_length=200)),
                ('latitudeNum', models.DecimalField(blank=True, decimal_places=8, max_digits=200, null=True)),
                ('longitudeNum', models.DecimalField(blank=True, decimal_places=8, max_digits=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
