# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightprice', '0010_auto_20170924_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='razaoSocialName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
